### ISSUE TITLE
Can note create unknown type 'http://schemas.uipath.com/workflow/activities)ReadRange' at source UiPath.Core.Activities

### ISSUE THREAD

**Issue by jignesh88** [UiPath/ReFrameWork#5]
Hi there,

I have just download ReFramework and I am getting following error message? 

Am I missing something?

**Comment by mihhdu** [comment]
Hi jignesh,

It seems to me like the error you are getting is that your ReadRange activity's signature is different than the one in the project. 

What version of UiPath Studio are you using?

**Comment by jignesh88** [comment]
Ahh..Figured out. Excel package was missing from my UiPath installation as I have reinstalled recently.
All good!!.

**Comment by jignesh88** [comment]
Closing issue!!
